name = "MamboPower"
uuid = "5281a46e-aa0a-46ed-be3d-cbc209784157"
authors = ["Manho Joung"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
